import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "../../apps/*/index.html",
    "../../apps/*/src/**/*.{js,ts,jsx,tsx}",
    "../../packages/ui/src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#adc6ff",
        "surface-container-highest": "#32353c",
        "inverse-surface": "#e1e2ec",
        "on-tertiary-container": "#461f00",
        "on-background": "#e1e2ec",
        "background": "#10131a",
        "on-surface-variant": "#c2c6d6",
        "on-secondary-container": "#c4abff",
        "outline-variant": "#424754",
        "on-tertiary-fixed-variant": "#723600",
        "inverse-on-surface": "#2e3038",
        "tertiary-container": "#df7412",
        "on-tertiary": "#502400",
        "secondary-fixed-dim": "#d0bcff",
        "on-primary-fixed": "#001a42",
        "tertiary": "#ffb786",
        "on-primary-container": "#00285d",
        "surface-container-low": "#191b23",
        "outline": "#8c909f",
        "surface-container-lowest": "#0b0e15",
        "surface-tint": "#adc6ff",
        "on-primary": "#002e6a",
        "surface-variant": "#32353c",
        "tertiary-fixed-dim": "#ffb786",
        "primary-fixed-dim": "#adc6ff",
        "inverse-primary": "#005ac2",
        "surface-bright": "#363941",
        "primary-container": "#4d8eff",
        "on-surface": "#e1e2ec",
        "error": "#ffb4ab",
        "on-secondary": "#3c0091",
        "on-error": "#690005",
        "surface-container": "#1d2027",
        "surface-dim": "#10131a",
        "error-container": "#93000a",
        "primary-fixed": "#d8e2ff",
        "secondary-container": "#571bc1",
        "tertiary-fixed": "#ffdcc6",
        "secondary": "#d0bcff",
        "on-tertiary-fixed": "#311400",
        "on-secondary-fixed-variant": "#5516be",
        "secondary-fixed": "#e9ddff",
        "on-primary-fixed-variant": "#004395",
        "surface-container-high": "#272a31",
        "on-secondary-fixed": "#23005c",
        "surface": "#10131a",
        "on-error-container": "#ffdad6"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
        "card": "20px"
      },
      spacing: {
        "sm": "8px",
        "xl": "32px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "unit": "8px",
        "lg": "24px",
        "container-max": "1280px",
        "xs": "4px",
        "md": "16px",
        "xxl": "64px"
      },
      fontFamily: {
        "headline-sm": ["Satoshi"],
        "body-lg": ["Inter"],
        "display-lg-mobile": ["Satoshi"],
        "display-lg": ["Satoshi"],
        "body-sm": ["Inter"],
        "body-md": ["Inter"],
        "label-md": ["Inter"],
        "headline-md": ["Satoshi"]
      },
      fontSize: {
        "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "display-lg-mobile": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
};

export default config;
